name: Relay Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./relay
          push: true
          tags: driesboy/p2p-file-transfer:latest
          build-args: BUILD_ID=${{ github.sha }}
          platforms: linux/amd64,linux/arm64
